### ISSUE TITLE
Add option to specify HCI by MAC address.

### ISSUE THREAD

**Issue by skynetforcats** [araines/homeassistant-thermoplus-ble#14]
When using multiple BT dongles the number they are assigned by the OS sometimes change, for whatever reason. So it would be usefull if the MAC address could be used to specify which HCI device to use.

**Comment by araines** [comment]
I'll have to look in to how this might be possible through the Python hardware interfaces.  I know on a very simple level it is a device number, but I can see the benefit of what you'd like to do here.  If you're able to contribute, that would be hugely welcomed!

**Comment by skynetforcats** [comment]
I doubt I could submit an actual solution. But I can see that [ble_monitor](https://github.com/custom-components/ble_monitor/blob/master/custom_components/ble_monitor/__init__.py) which also use aioble has done something similar.
Although their code looks more complex I don't think the actual conversion from mac to hci would have to be a lot of code. But honestly I don't understand enough of it to say for sure.

**Comment by araines** [comment]
I'm recommending that people use ble_monitor (https://github.com/custom-components/ble_monitor) from this point forwards.  The maintainers there have kindly integrated support for Thermoplus sensors as of version 3.1 (currently in beta).  It also has a whole host of other features beyond this component which I think are great.
