### ISSUE TITLE
No sensors found

### ISSUE THREAD

**Issue by jasonwragg** [araines/homeassistant-thermoplus-ble#3]
Installed using HACs and added to yaml, I have 1 new meter but its not found.

**Comment by araines** [comment]
Thanks for reporting an issue.

Can you please confirm what sensor you're using?  Also what hardware are you running Home Assistant on?  I've tested with a Raspberry Pi 4 which has built-in bluetooth, and I had success with a rPi 2B with a bluetooth adapter too (although I wouldn't recommend an rPi 2 for HA).

The other thing to mention is it can take a minute or two to do the initial pairing process, so try putting the sensor near to your HA system and giving it a few minutes to detect.

**Comment by jasonwragg** [comment]
I have HA running on a rPi4.

This is the sensor: https://www.amazon.co.uk/gp/product/B08BHPS45S/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

Its been installed for a few hours now but nothing has happened.

Jason

**Comment by araines** [comment]
Are you able to set logging to `info` for this integration and then report back with an excerpt of the logs?  It will output a stream of logs every minute, just one run will do.  Also are you able to confirm this works with the Sensor Blue app the device is meant to work with?

**Comment by jasonwragg** [comment]
Strangely it’s started working after I installed this.

https://github.com/custom-components/ble_monitor

Not sure if it was a co-incidence or it had something to do with it but it working now.

**Comment by araines** [comment]
Ah interesting, thanks.  Did you need to do these steps at all?

> This is usually only needed for alternative installations of Home Assistant that only install Home Assistant core.
> to grant access:
```
sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3\``
```
> to verify:
```
sudo getcap `readlink -f \`which python3\``
```

**Comment by jasonwragg** [comment]
Yes I did.

**Comment by araines** [comment]
Excellent, thanks for the feedback.  For some reason when I did it and others who have used/tested it for me haven't needed to do anything with permissions on Python, but clearly there is sometimes a need for this to happen.  Having looked at the rest of the library and the installation instructions I couldn't see anything else obvious which might cause the problems you were seeing.

I'll leave this issue open for now, my expectation is that adding some more detail to the README for people to try playing with the capabilities of python like that if they have problems will hopefully resolve this issue.

Thanks again for reporting - it all helps 👍

**Comment by madninjaskillz** [comment]
I have currently two full HA installs, one on a raspberry pi 3 and one as a VM inside unraid (full VM using the full OS virtual disk, not a core install nor a docker) - my pi3 has a dead wireless chip so neither BT nor WIFI works, so I have connected a dongle - and had zero joy. I've tried same dongle in the VM (with passthru) with similar luck. Obviously it may be a dongle which is unsupported in linux or I may be doing something wrong. What is the best way to diagnose? 

I'm using this sensor (purchased BECAUSE of this repo)
https://www.amazon.co.uk/gp/product/B08BHPS45S/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1
and the dongle is listed in unraid as:
 Cambridge Silicon Radio Bluetooth Dongle (HCI mode) (0a12:0001)

**Comment by araines** [comment]
@madninjaskillz the first place to look would be in the HA logs - if you can see any errors being thrown by this integration when starting up (you may need to restart HA).  If you can't see anything in there, you can change the logging level for this integration to `info` or even `debug` to get more information in the logs.  Beware, the `debug` level prints a LOT of data and I wouldn't recommend running all the time at that level.

In debug mode, it will log every BLE packet it has seen every minute with all the data it has managed to parse.  I guess if you can see this happening, that suggests that your bluetooth adapter is working properly, but for some reason the sensor is not being detected.

Also depending on your install you may need to do the `getcap/setcap` steps as described [above](https://github.com/araines/homeassistant-thermoplus-ble/issues/3#issuecomment-756686332).

Finally, if you dongle has an activity LED in it, if its on/blinking a lot that suggests its doing something!

My other thought is that if the device has multiple interfaces (which may well be the case in both of your situations), this integration currently just attempts to work with the first one.  I'd need to do some small modifications to the code to allow for that to be made configurable.  In case you fancy hacking it to find out, the interface it uses is defined here:
https://github.com/araines/homeassistant-thermoplus-ble/blob/master/custom_components/thermoplus_ble/ble.py#L66

(interface 0 is the first interface, you could try incrementing that number to see if you have any luck).


Note to self: improve documentation around troubleshooting techniques.

**Comment by madninjaskillz** [comment]
So what I've done:
* Ive installed Debian 10.7 on a real PC. 
* I've confirmed the bluetooth works within X
* Setup HA - then rebooted
* Added HACS - then rebooted
* Added the custom repo - the rebooted
* Added the config to config.yaml:
```
sensor:
  - platform: thermoplus_ble
  ```
* rebooted

Here is my log file - I'm at the point I'm thinking either I'm doing something very wrong, my bluetooth dongle is weird or the hardware has changed - Tried three platforms and the only common denominators are the sensor (which works in sensor blue) and the bluetooth dongle.

I will say with the dongle in windows i can attempt to pair with the dongle (it fails, but it IS visible)

[halog.txt](https://github.com/araines/homeassistant-thermoplus-ble/files/5802973/halog.txt)
```
logger:
  default: info
  logs:
    custom_components.thermoplus_ble.sensor: debug
```

**Comment by araines** [comment]
```
2021-01-12 15:02:33 DEBUG (SyncWorker_2) [custom_components.thermoplus_ble.sensor] Processing scanner data
2021-01-12 15:02:33 INFO (SyncWorker_2) [custom_components.thermoplus_ble.sensor] 2 HCI events received
2021-01-12 15:02:33 INFO (SyncWorker_2) [custom_components.thermoplus_ble.sensor] 0 known sensors
```

This here looks like it is scanning BLE HCI events, which would suggest the bluetooth adapter is working.  However, only 2 events is awfully small, and then none of them were advertising packets.  If your home is anything like mine, I'd expect to see a MUCH larger number than 2 and a whole bunch of advertising packets too.  At the moment this integration will just ignore anything which isn't an advertising packet.

Just for comparisons sake, here is a run I've just done on my system:
```
2021-01-12 17:27:02 INFO (SyncWorker_1) [custom_components.thermoplus_ble.sensor] 106 HCI events received
2021-01-12 17:27:02 INFO (SyncWorker_1) [custom_components.thermoplus_ble.sensor] Found new ThermoBeacon sensor at 9B:B0:00:00:02:60
2021-01-12 17:27:02 INFO (SyncWorker_1) [custom_components.thermoplus_ble.sensor] Found new ThermoBeacon sensor at 9B:B4:00:00:0A:97
2021-01-12 17:27:02 INFO (SyncWorker_1) [custom_components.thermoplus_ble.sensor] Found new ThermoBeacon sensor at 9B:B0:00:00:03:22
2021-01-12 17:27:02 INFO (SyncWorker_1) [custom_components.thermoplus_ble.sensor] 3 known sensors
```

I'll try to do a bit of digging this evening about figuring out which adapter/interfaces are recognised by the system and see if there is something that can be done about that.

**Comment by madninjaskillz** [comment]
I'm in a shed away from the house and outside of the therm and my phone i dont think there are any powered up bluetooth devices so the count possibly makes sense. If I use Bluetooth LE Scanner on my android, it sees 5 things (ThermoBeacon and 4 unknowns) which might be down to a better device having more range. Is it possible to open the packets it sees to see if the device is just returning a slightly different packet to what you expect and thus ignoring it?

**Comment by araines** [comment]
OK that might make more sense.

I've just added some additional debug and configuration options to the integration (#5).  If you upgrade to version 0.2.0 you'll be able to use them.  The `hci_dump` configuration will allow you to dump all detected bluetooth HCI packets.  The `hci_interface` configuration will allow you to select which device to use on your system.  The README / Troubleshooting documentation has been updated to suit too: https://github.com/araines/homeassistant-thermoplus-ble/blob/master/troubleshooting.md

Also it's entirely possible your phone is a much better bluetooth device and so can "see" further.  Whilst debugging, I'd suggest moving your sensor as close to your bluetooth host as possible to ensure range is not a factor.

Let me know how you get on!

**Comment by madninjaskillz** [comment]
Thanks for your patience!

To rule out something from the possibilities, ive done a (yet another lol) fresh debian based supervised install on an old laptop (with built in bluetooth) - and I'm seeing the exact same thing

have added the logging
```
2021-01-12 21:42:08 INFO (SyncWorker_4) [custom_components.thermoplus_ble.ble] Starting scanner thread on interface 0
2021-01-12 21:42:09 INFO (SyncWorker_4) [custom_components.thermoplus_ble.ble] Starting scanner thread on interface 0
2021-01-12 21:42:09 INFO (SyncWorker_4) [custom_components.thermoplus_ble.sensor] 2 HCI events received
2021-01-12 21:42:09 INFO (SyncWorker_4) [custom_components.thermoplus_ble.sensor] HCI DUMP: 040e04010b2001
2021-01-12 21:42:09 INFO (SyncWorker_4) [custom_components.thermoplus_ble.sensor] HCI DUMP: 040e04010c2001
2021-01-12 21:42:09 INFO (SyncWorker_4) [custom_components.thermoplus_ble.sensor] 0 known sensors
2021-01-12 21:43:09 INFO (SyncWorker_4) [custom_components.thermoplus_ble.ble] Starting scanner thread on interface 0
2021-01-12 21:43:09 INFO (SyncWorker_4) [custom_components.thermoplus_ble.sensor] 2 HCI events received
2021-01-12 21:43:09 INFO (SyncWorker_4) [custom_components.thermoplus_ble.sensor] HCI DUMP: 040e04010b2001
2021-01-12 21:43:09 INFO (SyncWorker_4) [custom_components.thermoplus_ble.sensor] HCI DUMP: 040e04010c2001
2021-01-12 21:43:09 INFO (SyncWorker_4) [custom_components.thermoplus_ble.sensor] 0 known sensors
```

hope this gives you a hint because I'm out of ideas lol!

**Comment by araines** [comment]
Those look like BLE scan response packets coming from the following MAC addresses (assuming [this tool](https://reelyactive.github.io/advlib/) is correct)
```
01:20:0b:01:04
01:20:0c:01:04
```

Both have no actual data in them.  The data from the sensors is far larger/longer.  I'm not sure if you have any other means of finding out what those MAC addresses belong to?

Have you tried a different HCI interface just in case (details of how to do that now in the latest versions' docs)?

Only other idea I have right now would be to try to manually capture all the bluetooth packets your adapter is able to see, throwing them through Wireshark or similar to see what comes up.

**Comment by madninjaskillz** [comment]
Something so obvious occurs to me. Is there a chance that the lack of detection I am seeing is due to my bluetooth devices not being 4.0 and thus not supporting BLE? (i don't know if they are or not but i strongly suspect on the laptop it is not) I have ordered a 4.0 BLE adapter (and am about to install HASS on my GPD win as i KNOW that is 4.0) and will report back if I have any success. It might be worth pointing out that BT4.0 is required (even though that is a given and I am ashamed I didnt even consider it)

**Comment by araines** [comment]
Well I'm ashamed to admit that didn't occur to me to check either!  Please let me know how you get on, I'll make sure to update the docs as well.

**Comment by madninjaskillz** [comment]
Yup, that was entirely the issue - my old GPD Win (with a swolen battery) actually makes a great replacement for the raspberry pi and everything is working lovely - sorry for wasting your time.

**Comment by araines** [comment]
Excellent news!  I'm glad you've got it working.  Also it was far from a waste of my time, it helped me realise that the documentation and debugging was a bit challenging, so a good opportunity to make some needed improvements!
