### ISSUE TITLE
FYI these two sensors are also working for me

### ISSUE THREAD

**Issue by skynetforcats** [araines/homeassistant-thermoplus-ble#6]
I forgot if I already told you. These two also work for me, if you want to update the readme.

[Brifit Bluetooth Thermometer, Hygrometer Wireless Thermometer ](https://www.amazon.de/gp/product/B085C963Y3/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1)
![image](https://user-images.githubusercontent.com/36438756/105423291-8a6f9780-5c45-11eb-9b1c-0ee0b8e6beb5.png)

[Brifit Bluetooth thermometer, hygrometer, wireless mini thermometer, hygrometer with high accuracy, indoor thermometer with app, data storage for home garage, greenhouse, wine cellar, office ](https://www.amazon.de/gp/product/B08MBPRMFZ/ref=ppx_yo_dt_b_asin_title_o08_s00?ie=UTF8&psc=1)
![image](https://user-images.githubusercontent.com/36438756/105423320-96f3f000-5c45-11eb-81a0-f17f8a90551b.png)

**Comment by araines** [comment]
Thanks, I'll get those added
