### ISSUE TITLE
Negative temperature shows as very high number in Home Assistant sensor

### ISSUE THREAD

**Issue by kelu16** [araines/homeassistant-thermoplus-ble#9]
Hi,
I have one of my thermometers on the outside and the real temperature of -1.13°C is displayed in Home Assistant as 4.094,88 °C. As soon as the temperature is above 0 °C the value is correctly shown in HA.
This looks like an overflow problem with an unsigned 12 bit data type.

Do you have an idea how to fix this?

**Comment by araines** [comment]
Available in v0.2.1
